config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users


  # get 'home', to: 'pages#home', as: :home

  resources :notes
  resources :projects_users
  resources :users
  resources :tasks
  resources :projects do
    resources :tasks
  end

  resources :projects do
    member do
      put :active
      put :deactive
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :project
  belongs_to :user

  # validates :project_id, uniqueness { scope: :user_id }
end

app/controllers/projects_users_controller.rb
class ProjectsUsersController < ApplicationController
  before_action :set_projects_user, only: [:show, :edit, :update, :destroy]

  # GET /projects_users
  # GET /projects_users.json
  def index
    @projects_users = ProjectsUser.all
    @projects_users = ProjectsUser.page(params[:page]).per(3)
  end

  # GET /projects_users/1
  # GET /projects_users/1.json
  def show
  end

  # GET /projects_users/new
  def new
    @projects_user = ProjectsUser.new
  end

  # GET /projects_users/1/edit
  def edit
  end

  # POST /projects_users
  # POST /projects_users.json
  def create
    @projects_user = ProjectsUser.new(projects_user_params)

    respond_to do |format|
      if @projects_user.save
        format.html { redirect_to @projects_user, notice: 'Projects user was successfully created.' }
        format.json { render :show, status: :created, location: @projects_user }
      else
        format.html { render :new }
        format.json { render json: @projects_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects_users/1
  # PATCH/PUT /projects_users/1.json
  def update
    respond_to do |format|
      if @projects_user.update(projects_user_params)
        format.html { redirect_to @projects_user, notice: 'Projects user was successfully updated.' }
        format.json { render :show, status: :ok, location: @projects_user }
      else
        format.html { render :edit }
        format.json { render json: @projects_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects_users/1
  # DELETE /projects_users/1.json
  def destroy
    @projects_user.destroy
    respond_to do |format|
      format.html { redirect_to projects_users_url, notice: 'Projects user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projects_user
      @projects_user = ProjectsUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projects_user_params
      params.require(:projects_user).permit(:project_id, :user_id)
    end
end

app/helpers/projects_users_helper.rb
module ProjectsUsersHelper
end

app/views/projects_users/_form.html.erb
<%= form_with(model: projects_user, local: true) do |form| %>
  <% if projects_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projects_user.errors.count, "error") %> prohibited this projects_user from being saved:</h2>

      <ul>
        <% projects_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, class: "form-control", placeholder: "project_id" %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "form-control", placeholder: "user_id" %>
  </div>

  <div class="actions text-center" style="padding-top: 12px">
    <%= form.submit class:"btn btn-light btn-outline-dark"%>
  </div>
<% end %>

app/views/projects_users/edit.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Home</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>

<h1>Editing User</h1>

<%= render 'form', projects_user: @projects_user %>
<br>
<div class="text-center">
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Show', @projects_user %>
  </div>
   |
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Back', projects_users_path %>
  </div>
</div>

app/views/projects_users/index.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Project_users</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <p id="notice"><%= notice %></p>

      <h1>Projects Users</h1>

      <div class="element-box">
        <h6 class="element-header">
          <h3 class="text-right">
            <div class="btn btn-light btn-outline-dark">
              <%= link_to 'New Projects User', new_projects_user_path %>
            </div>
          </h3>

          <table>
            <thead>
              <tr>
                <th>Project</th>
                <th>User</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @projects_users.each do |projects_user| %>
                <tr>
                  <td><%= projects_user.project_id %></td>
                  <td><%= projects_user.user_id %></td>
                  <td><%= link_to 'Show', projects_user, class:"btn btn-outline-dark"  %></td>
                  <td><%= link_to 'Edit', edit_projects_user_path(projects_user), class:"btn btn-outline-dark"  %></td>
                  <td><%= link_to 'Destroy', projects_user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>


        </h6>

        <%= paginate @projects_users %>
        <%= page_entries_info @projects_users %>
      </div>
    </div>
  </div>
</div>

app/views/projects_users/new.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Home/project_users/new</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>
<h1>New Projects User</h1>

<%= render 'form', projects_user: @projects_user %>

<h3 class="text-center ">
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Back', projects_users_path %>
  </div>
</h3>

app/views/projects_users/show.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Home/projects_users/show</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>
<p id="notice"><%= notice %></p>

<div class="text-center">
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Edit', edit_projects_user_path(@projects_user) %>
  </div>
  |
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Back', projects_users_path %>
  </div>
</div>

<p>
  <strong>Project:</strong>
  <%= @projects_user.project_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @projects_user.user_id %>
</p>