config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users


  # get 'home', to: 'pages#home', as: :home

  resources :notes
  resources :projects_users
  resources :users
  resources :tasks
  resources :projects do
    resources :tasks
  end

  resources :projects do
    member do
      put :active
      put :deactive
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :title,:status,:start_date,:estimated_time, presence: true
  validates :description, length: { maximum: 500 }

  before_validation :set_status

  before_validation :set_start_date

  after_destroy :task_destroy_message

  def set_status
    self.status = 'Active' if self.status.blank?
  end

  def set_start_date
    self.start_date = Time.now if self.start_date.blank?
  end

  def task_destroy_message
    puts 'Task destroyed'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @project.tasks.page(params[:page]).per(3)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find_by(id: params[:project_id])

      redirect_to projects_path if @project.blank?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :status, :user_id, :start_date, :end_date, :spend_time, :estimated_time)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, url: [@project, task], local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title"%>
    <% if task.errors.any? %>
      <p>
        <%= task.errors.messages[:title].join(', ') %>
      </p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", placeholder: "Description"  %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, class: "form-control", placeholder: "Status"  %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%# <%= form.text_field :user_id, class: "form-control", placeholder: "User_id"  %>
    <%= form.select(:user_id, User.pluck(:name, :id), { prompt: 'Select'},class: "form-control") %>
    <% if task.errors.any? %>
      <p>
        <%= task.errors.messages[:user_id].join(', ') %>
      </p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "form-control", placeholder: "Start_date"  %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: "form-control", placeholder: "End_date"  %>
  </div>

  <div class="field">
    <%= form.label :spend_time %>
    <%= form.text_field :spend_time, class: "form-control", placeholder: "Spend_time"  %>
  </div>

  <div class="field">
    <%= form.label :estimated_time %>
    <%= form.text_field :estimated_time, class: "form-control", placeholder: "Estimated_time"  %>
    <% if task.errors.any? %>
      <p>
        <%= task.errors.messages[:estimated_time].join(', ') %>
      </p>
    <% end %>
  </div>

  <div class="actions text-center" style="padding-top: 12px">
    <%= form.submit class:"btn btn-light btn-outline-dark"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<div class="text-center">
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Show', project_task_path(@project, @task) %>
  </div>
   |
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Back', project_tasks_path(@project) %>
  </div>
</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1><b>Tasks</b></h1>

<h3 class="text-right">
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'New Task', new_project_task_path(@project, @task) %>
  </div>
</h3>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Project</th>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>User</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Spend time</th>
      <th>Estimated time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.project.title, task.project %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= link_to task.user.name, task.user %></td>
        <td><%= task.start_date.strftime("%m/%d/%Y %H:%M") %></td>
        <td><%= task.end_date.strftime("%m/%d/%Y %H:%M") %></td>
        <td><%= task.spend_time %></td>
        <td><%= task.estimated_time %></td>
        <td><%= link_to 'Show', project_tasks_path(@project, @task), class:"btn btn-outline-dark" %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project, task), class:"btn btn-outline-dark" %></td>
        <td><%= link_to 'Destroy', url_for([@project, task]), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<%= paginate @tasks %>
<%= page_entries_info @tasks %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<h3 class="text-center ">
  <div class="btn btn-light btn-outline-dark">
    <%= link_to '<< Back', project_path(@project) %>
  </div>
</h3>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
  </div>
  |
  <div class="btn btn-light btn-outline-dark">
    <%= link_to 'Back', project_path(@project) %>
  </div>
</div>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<p>
  <strong>Spend time:</strong>
  <%= @task.spend_time %>
</p>

<p>
  <strong>Estimated time:</strong>
  <%= @task.estimated_time %>
</p>