config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users


  # get 'home', to: 'pages#home', as: :home

  resources :notes
  resources :projects_users
  resources :users
  resources :tasks
  resources :projects do
    resources :tasks
  end

  resources :projects do
    member do
      put :active
      put :deactive
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_and_belongs_to_many :users
  belongs_to :manager, class_name: "User", optional: true

  validates :title, presence: true
  validates :start_date, presence: true
  validates :description, length: { maximum: 500 }
  validates :website, format: { with: /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }
  before_validation :set_start_date

  after_destroy :project_destroy_message

  def set_start_date
    self.start_date = Time.now if self.start_date.blank?
  end

  def project_destroy_message
    puts "Project destroyed"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @projects = Project.page(params[:page]).per(3)
    @projects = @projects.where(active: (params[:active] == '1')) if params[:active].present?
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def active
    @project.active = true
    @project.save
    redirect_to projects_path, notice: 'Project was successfully activated.'
  end

  def deactive
    @project.update(active: false)
    puts @project.errors.messages
    redirect_to projects_path, notice: 'Project was successfully deactivated.'
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :manager_id, :website, :start_date, :end_date, :active)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title"  %>
    <% if project.errors.any? %>
      <p>
        <%= project.errors.messages[:title].join(', ') %>
      </p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="field">
    <%= form.label :manager_id %>
    <%# <%= form.number_field :manager_id, class: "form-control", placeholder: "Manager_id" %>
    <%= form.select(:manager_id, User.pluck(:name, :id), { prompt: 'Select'},class: "form-control") %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, class: "form-control", placeholder: "Website" %>
    <% if project.errors.any? %>
      <p>
        <%= project.errors.messages[:website].join(', ') %>
      </p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :Active %>
    <%= form.check_box :active,placeholder: "Active" %>
  </div>

  <div class="actions text-center" style="padding-top: 12px">
    <%= form.submit class:"btn btn-light btn-outline-dark"%>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Home/projects/edit</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <h6 class="element-header">
        Editing Project
      </h6>
      <div class="element-box">
        <%= render 'form', project: @project %>
        <br>
        <div class="text-center">
          <div class="btn btn-light btn-outline-dark">
            <%= link_to 'Show', @project %>
          </div>
          |
          <div class="btn btn-light btn-outline-dark">
            <%= link_to 'Back', projects_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Home/project</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <p id="notice"><%= notice %></p>
      <h6 class="element-header">
        <b>Projects</b>
      </h6>
      <h3 class="text-right">
        <div class="btn btn-light btn-outline-dark">
          <%= link_to 'New Project', new_project_path %>
        </div>
      </h3>
      <div class="element-box">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Manager</th>
              <th>Website</th>
              <th>Start date</th>
              <th>End date</th>
              <th>Active</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @projects.each do |project| %>
            <tr>
              <td><%= project.title %></td>
              <td><%= project.description %></td>
              <td><%= link_to project.manager.name, project.manager %></td>
              <td><%= link_to project.website, "http://www.google.de/search?q=#{project.website}", target: "_blank"%></td>
              <td><%= project.start_date.strftime("%m/%d/%Y %H:%M") %></td>
              <td><%= project.end_date.strftime("%m/%d/%Y %H:%M") %></td>
              <td><%= project.active ? 'yes' : 'no' %></td>
              <td><%= link_to 'Show', project, class:"btn btn-outline-dark" %></td>
              <td><%= link_to 'Edit', edit_project_path(project), class:"btn btn-outline-dark" %></td>
              <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %></td>
              <td><% if project.active %>
                <%= link_to "Deactive", deactive_project_path(project), method: :put, class: "btn btn-outline-dark", data: { confirm: 'Are you sure?' } %>
                <% else %>
                <%= link_to "Active", active_project_path(project), method: :put, class: "btn btn-outline-dark", data: { confirm: 'Are you sure?' } %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <br>
        <%= paginate @projects %>
        <%= page_entries_info @projects %>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Home/project/mew</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <h6 class="element-header">
        New Projects
      </h6>
      <div class="element-box">
        <%= render 'form', project: @project %>

        <h3 class="text-center ">
          <div class="btn btn-light btn-outline-dark">
            <%= link_to 'Back', projects_path %>
          </div>
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :breadcrumb do %>
  <!--------------------
  START - Breadcrumbs
  -------------------->
  <ul class="breadcrumb">
    <li class="breadcrumb-item">
      <span>Home/project/show</span>
    </li>
  </ul>
  <!--------------------
  END - Breadcrumbs
  -------------------->
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <h6 class="element-header">
        <p id="notice"><%= notice %></p>
        My Projects
      </h6>
      <div class="element-box">
        <h1><b><%= @project.title %> Detail</b></h1>

        <h3 class="text-center">
          <div class="btn btn-light btn-outline-dark">
            <%= link_to 'Edit', edit_project_path(@project) %>
          </div>
          |
          <div class="btn btn-light btn-outline-dark">
            <%= link_to 'Back', projects_path(@project) %>
          </div>
          |
          <div class="btn btn-light btn-outline-dark">
            <%= link_to 'New Task ', new_project_task_path(@project.id) %>
          </div>
        </h3>

        <p>
          <strong>Title:</strong>
          <%= @project.title %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @project.description %>
        </p>

        <p>
          <strong>Manager:</strong>
          <%= @project.manager_id %>
        </p>

        <p>
          <strong>Website:</strong>
          <%= @project.website %>
        </p>

        <p>
          <strong>Start date:</strong>
          <%= @project.start_date %>
        </p>

        <p>
          <strong>End date:</strong>
          <%= @project.end_date %>
        </p>

        <p>
          <strong>Active:</strong>
          <%= @project.active %>
        </p>

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Status</th>
              <th>User</th>
              <th>Start date</th>
              <th>End date</th>
              <th>Spend time</th>
              <th>Estimated time</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @project.tasks.each do |task| %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.description %></td>
              <td><%= task.status %></td>
              <td><%= link_to task.user.name, task.user %></td>
              <td><%= task.start_date.strftime("%m/%d/%Y %H:%M") %></td>
              <td><%= task.end_date.strftime("%m/%d/%Y %H:%M") %></td>
              <td><%= task.spend_time %></td>
              <td><%= task.estimated_time %></td>
              <td><%= link_to 'Show', project_task_path(@project, task), class:"btn btn-outline-dark" %></td>
              <td><%= link_to 'Edit', edit_project_task_path(@project, task), class:"btn btn-outline-dark" %></td>
              <td><%= link_to 'Destroy', url_for([@project, task]), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>